version: "3.8"
services:
  portal01:
    container_name: neix-portal01
    image: txe1/portal-simple
    ports:
      - "3000:80"
    environment:
      TITLE: "Joyce, Jiang-QY"
  portal02:
    container_name: neix-portal02
    image: txe1/portal-simple
    ports:
      - "3001:80"
    environment:
      TITLE: "Justin, Tan-XE"
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - portal01
      - portal02